### PR TITLE
Extend delete one feedback api to support delete all feedbacks.

### PR DESCRIPTION
**Pull request by wilsonhsu98**
1) Extend delete one feedback api to support delete all feedbacks.
2) Adjust unit test.

### CODE REVIEW

**Comment by jonascheng** [comment]
Hi Wilson,

  Do you intent to provide delete all feedback to frontend?
  If you would like to enhance deleteOneSurvey, you should
  Achieve this inside back-end instead of exporting to frontend.

  I also found another issue in deleteFeedback, you don't need to provide clientid in this case, please correct me.

Thanks,

**Comment by jonascheng** [comment]
BTW, did you also find the root cause of coveralls failure because I saw you modified package.json script?

**Comment by wilsonhsu98** [comment]
Hi Jonas,

I'm not sure delete all feedback will provide for frontend or not.
But I think frontend might call this API someday.
So I exported it
If you think that was unnecessary, I'll remove the export from s-function.

I extended deleteFeedbacks function,
We can provide both surveyid and clientid to this function, then will delete single feedback.
Or just provide a surveyid, it will delete all feedback.
Which part unclear let you misunderstanding.

For the package.json script I've revised, it's compatible for windows & mac.

Thanks.

**Comment by jonascheng** [comment]
Hi Wilson,

  It's ok to provide API to frontend, and no concern for this now.

  Another deleteFeedbacks issue, I misunderstood your code and I didn't make myself clear.
  I meant you should be able to invoke dynamodb api without providing clientid instead of looping all feedbacks. In short, please check if you could remove listFeedbacks to save DDB multiple access time. Thanks!

      } else if (event.surveyid && process.env.SERVERLESS_FEEDBACKTABLE) {
 -    else {		 +        listFeedbacks(event).then(response => {
 -      return callback(new Error("400 Bad Request: Missing parameters: " + JSON.stringify(event)), null);		 +          Promise.all(response.feedbacks.map(item => deleteFeedbacks(item))).then(() => {
 -    }		 +            resolve({});
 +          });
 +        }).catch(err => {
 +          reject(err, null);
 +        });


Thanks,
Jonas

**Comment by wilsonhsu98** [comment]
Hi Jonas,

I know, it's very ridiculous to delete each feedback in loop.
But it seems DDB can not delete data with if the condition is combined primary key.
Please see [stackoverflow](http://stackoverflow.com/questions/9154264/what-is-the-recomended-way-to-delete-a-large-number-of-items-from-dynamodb)
Any idea?

Thanks

**Comment by sypannapis** [comment]
Hi both,

Sorry to jump in. 
I'm not sure if my understanding is correct. As mentioned in the stackoverflow link mentioned by Wilson, maybe [batchWrite()](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/DynamoDB/DocumentClient.html#batchWrite-property) could do the trick to delete all items in one shot.

Anderson

**Comment by jonascheng** [comment]
Hi both,

  I got the point and realize DDB limitation.
  I'm fine to keep current solution, but remind you to only delete the survey from survey table after
  All feedback items are removed successfully.

Thanks,
Jonas

**Comment by wilsonhsu98** [comment]
Hi Jonas,

As Anderson's command,  batchWrite() can support delete & put request in array.
So I revised the code.

Thanks,
Wilson

**Pull request merged**
